/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/



//===================================================================================
// Beat Surface Application
// A Real Time Percussive Stroke Detection and Classification System
//
// Georgia Tech Center for Music Technology
//===================================================================================


#include "../../JuceLibraryCode/JuceHeader.h"
#include "BeatSurfaceHeader.h"
#include "MainAppWindow.h"

//==================================================================================
class BeatSurfaceApplication  : public JUCEApplication
{
public:
    //==============================================================================
    BeatSurfaceApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // This method is where you should put your application's initialisation code..
        
        Desktop::getInstance().setOrientationsEnabled (Desktop::allOrientations);
        
        commandManager = new ApplicationCommandManager();
        commandManager->registerAllCommandsForTarget (this);
        
        
        sharedAudioDeviceManager = new AudioDeviceManager();
        sharedAudioDeviceManager->initialise(BeatSurfaceBase::iNumInputChannels,
                                             BeatSurfaceBase::iNumOutputChannels, 0, true, String::empty, 0);

        
        
        // Place Beat Surface Interface / Engine Here ???
        
        
        
        mainWindow = new MainAppWindow();
    }

    void shutdown()
    {
        // Add your application's shutdown code here..
        mainWindow = nullptr; // (deletes our window)
        
        commandManager = nullptr;
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    
    
    //==============================================================================
    
    // Return the set of all commands that this target can perform..
    void getAllCommands (Array <CommandID>& commands)
    {
        const CommandID ids[] =
        {
            CommandIDs::addClass,
            CommandIDs::deleteClass,
            CommandIDs::currentClass,
            
            CommandIDs::recordTraining,
            CommandIDs::doneTraining,
            
            CommandIDs::startAudio,
            CommandIDs::stopAudio,
            
            CommandIDs::applySettings,
            
            CommandIDs::goToKioskMode,
            
            StandardApplicationCommandIDs::quit
        };
        
        commands.addArray(ids, numElementsInArray(ids));
    }
    

    
    void getCommandInfo (CommandID commandID, ApplicationCommandInfo& result)
    {
        switch (commandID)
        {
            case CommandIDs::addClass:
                result.setInfo ("Add New Class", "Adds a new class of sounds", CommandCategories::TrainCommands, 0);
                result.addDefaultKeypress ('=', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::deleteClass:
                result.setInfo ("Delete Selected Class", "Deletes a selected class", CommandCategories::TrainCommands, 0);
                result.addDefaultKeypress ('-', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::currentClass:
                result.setInfo ("Select Class", "Selects the current class", CommandCategories::CommonCommands, 0);
                result.addDefaultKeypress ('t', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::recordTraining:
                result.setInfo ("Record Training", "Start currently selected class recording", CommandCategories::TrainCommands, 0);
                result.addDefaultKeypress ('3', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::doneTraining:
                result.setInfo ("Finished Training", "Finished currently selected training", CommandCategories::TrainCommands, 0);
                result.addDefaultKeypress ('4', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::startAudio:
                result.setInfo ("Start System", "Turns on detection and classification system", CommandCategories::PlayCommands, 0);
                result.addDefaultKeypress ('1', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::stopAudio:
                result.setInfo ("Stop System", "Turns off detection and classification system", CommandCategories::PlayCommands, 0);
                result.addDefaultKeypress ('2', ModifierKeys::commandModifier);
                break;
                
            case CommandIDs::applySettings:
                result.setInfo ("Apply Settings", "Save and apply settings", CommandCategories::SettingsCommands, 0);
                result.addDefaultKeypress ('5', ModifierKeys::commandModifier);
                break;
                
                
            #if ! JUCE_LINUX
            case CommandIDs::goToKioskMode:
                result.setInfo ("Show full-screen kiosk mode", String::empty, CommandCategories::CommonCommands, 0);
                result.addDefaultKeypress ('f', ModifierKeys::commandModifier);
                result.setTicked (Desktop::getInstance().getKioskModeComponent() != 0);
                break;
            #endif
                
            default:
                break;
        }
    }
    
    
    
    bool perform (const InvocationInfo& info)
    {
        switch (info.commandID)
        {
            case CommandIDs::addClass:
                // do something
                std::cout << "Add class" << std::endl;
                break;
                
            case CommandIDs::deleteClass:
                // do something
                std::cout << "Delete class" << std::endl;
                break;
                
            case CommandIDs::currentClass:
                // do something
                std::cout << "Current class" << std::endl;
                break;
                
                
                
            case CommandIDs::recordTraining:
                // do something
                std::cout << "Record Training" << std::endl;
                break;
                
            case CommandIDs::doneTraining:
                // do something
                std::cout << "Done Training" << std::endl;
                break;
                
                
                
            case CommandIDs::startAudio:
                // do something
                std::cout << "Start Audio" << std::endl;
                break;
                
            case CommandIDs::stopAudio:
                // do something
                std::cout << "Stop Audio" << std::endl;
                break;
                
                
                
            case CommandIDs::applySettings:
                // do something
                std::cout << "Apply Settings" << std::endl;
                break;
                
                
            #if ! JUCE_LINUX
            case CommandIDs::goToKioskMode:
            {
//                Desktop& desktop = Desktop::getInstance();
                
//                if (desktop.getKioskModeComponent() == nullptr)
//                    desktop.setKioskModeComponent (getTopLevelComponent());
//                else
//                    desktop.setKioskModeComponent (nullptr);
                
                break;
            }
            #endif
                
            default:
                return false;
        }
        
        return true;
    }
    
    
private:
    
    ScopedPointer<MainAppWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (BeatSurfaceApplication)
